const AE = 'https://ae-pic-a1.aliexpress-media.com/kf';
const CJI = 'https://cc-west-usa.oss-accelerate.aliyuncs.com';

// Product images
const IMGS = {
  // Product 1 — confirmed real CJDropshipping images
  slowFeeder:    `${CJI}/1d320cc0-82e7-40a8-a4f0-677ec0d56fdf.png`,
  lickMat:       `${AE}/Sd3e4e4bfe83d48979660c3cdd7e53290V.jpg_960x960q75.jpg`,
  pawCleaner:    `${AE}/S20747a7159fd41b5992d5305862de02ed.jpg_960x960q75.jpg`,
  catFountain:   `${AE}/Sdb9c39d769ce430eac49c3ff3ced4a6b9.png_960x960.png`,
  ledCollar:     `${AE}/Se8c8349e48ed4d5987e1eac04cf22a41c.jpg_960x960q75.jpg`,
  catBackpack:   `${AE}/S4823f3ffe3ee4d2e93c5e4cd975cd19eU.jpg_960x960q75.jpg`,
  dogBed:        `${AE}/Sdcf4f099a0d54f068d34e03111f2183fy.jpg_960x960q75.jpg`,
  slickerBrush:  `${AE}/S55eb7932a4194d3a8cc30bf63b9c45cff.jpg_960x960q75.jpg`,
  dogLeash:      `${AE}/S5daa242c599d4c9a91bd52f25e856bdbS.jpg_960x960q75.jpg`,
  squeakyToys:   `${AE}/Sa914b1a9b0a840debdf67ff8a0388f45Q.jpg_960x960q75.jpg`,
  puzzleFeeder:  `${AE}/S2b10bd6fb9d04b5abc75e39617a98c3b7.jpg_960x960q75.jpg`,
  carHammock:    `${AE}/S8d44db237aa14cebb1f1beed9ace13ccw.png_960x960.png`,
  travelBowls:   `${AE}/Sc2c0d9ee0d5f4a668d03add091de2dcb3.jpg_960x960q75.jpg`,
  harness:       `${AE}/S1c7559a29b20439abb6167a8134a5ab9V.jpg_960x960q75.jpg`,
  featherWand:   `${AE}/S67523ec27c114c05aa23975e8ff88e8fY.jpg_960x960q75.jpg`,
  windowPerch:   `${AE}/S3cef1cf463c24106a731db68b8b47294X.jpg_960x960q75.jpg`,
  laserToy:      `${AE}/Sfc6a4f7de1714eeb8092788d4507fa90q.jpg`,
  groomingGlove: `${AE}/Saa58b9bbbda1484da8267dfa3a62063cy.jpg_960x960q75.jpg`,
  catCave:       `${AE}/S2fb4e3ef438c49208aee50fb699b34b9d.jpg_960x960q75.jpg`,
};

export const products = [
  // ─── HERO 5 ───────────────────────────────────────────────────────────────
  {
    id: 1,
    slug: 'maze-slow-feeder-bowl',
    name: 'Maze Slow Feeder Bowl',
    shortName: 'Slow Feeder Bowl',
    category: 'Dogs',
    tag: 'Feeding',
    price: 24.99,
    comparePrice: 39.99,
    rating: 4.8,
    reviewCount: 1243,
    badge: 'Best Seller',
    badgeColor: 'bg-brand-500',
    image: IMGS.slowFeeder,
    images: [
      `${CJI}/1d320cc0-82e7-40a8-a4f0-677ec0d56fdf.png`,
      `${CJI}/82c29ab3-2793-44f3-9d4b-3e4cf1e9b979.jpeg`,
      `${CJI}/595d71ea-28aa-4ec0-a1ea-b0e7a5e1ed62.jpeg`,
    ],
    emoji: '🥣',
    stock: 47,
    soldCount: 1243,
    supplier: 'CJDropshipping',
    supplierProductId: '1653041912300969984',
    supplierSku: 'CJGY174846501AZ',
    supplierProductUrl: 'https://cjdropshipping.com/product/pet-dog-cat-slow-feeder-bowls-anti-choking-slow-feeder-dish-bowl-home-dog-eating-plate-anti-gulping-bowl-supplies-p-1653041912300969984.html',
    supplierCost: 2.50,
    shippingDays: '5–8 days',
    shortDescription: 'Vet-recommended slow feeder that prevents dangerous bloating, aids digestion, and makes mealtime fun.',
    description: 'Help your dog eat slower and healthier with our veterinarian-approved maze slow feeder. Dogs who eat too fast are at risk for bloating, gulping, and digestive issues. Our maze design forces dogs to work for each bite — slowing them down by up to 10x and turning mealtime into a stimulating puzzle they love.',
    features: [
      { icon: '🛡️', title: 'Vet Recommended', desc: 'Reduces dangerous bloating and gulping' },
      { icon: '🧠', title: 'Mental Stimulation', desc: 'Engages their mind during every meal' },
      { icon: '🍽️', title: 'Non-Slip Base', desc: 'Stays in place even for enthusiastic eaters' },
      { icon: '✨', title: 'Dishwasher Safe', desc: 'BPA-free, top-rack dishwasher friendly' },
    ],
    reviews: [
      { name: 'Sarah M.', rating: 5, date: 'May 2026', text: 'My dog used to inhale his food so fast he\'d get sick every week. This bowl completely fixed it. He actually enjoys his meals now — it\'s like a game for him!' },
      { name: 'Tom K.', rating: 5, date: 'April 2026', text: 'Our vet suggested a slow feeder and I\'m so glad I found this one. Great quality, easy to clean, and my boxer takes 10 minutes to finish instead of 30 seconds.' },
      { name: 'Linda R.', rating: 4, date: 'April 2026', text: 'Works perfectly for our medium-sized lab. Only thing I\'d change is a slightly deeper maze but otherwise 10/10.' },
    ],
  },
  {
    id: 2,
    slug: 'calming-lick-mat',
    name: 'Calming Lick Mat',
    shortName: 'Lick Mat',
    category: 'Dogs',
    tag: 'Anxiety Relief',
    price: 19.99,
    comparePrice: 34.99,
    rating: 4.9,
    reviewCount: 2891,
    badge: 'Fan Favorite',
    badgeColor: 'bg-emerald-500',
    image: IMGS.lickMat,
    images: [IMGS.lickMat, `${AE}/S0f7980c000a74b8d806d4a3149e21f206.jpg_960x960q75.jpg`, `${AE}/S1bb8396138c54b6ea9cdbb1774b40528o.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Pattern', options: ['Maze', 'Honeycomb', 'Flower', 'Grid'] },
      { type: 'Color', options: ['Blue', 'Green', 'Pink', 'Purple'] },
    ],
    emoji: '🐾',
    stock: 89,
    soldCount: 2891,
    supplier: 'CJDropshipping',
    supplierProductId: '2511110130591619600',
    supplierProductUrl: 'https://cjdropshipping.com/product/dog-slow-feeder-bowl-silicone-lick-mat-toy-p-2511110130591619600.html',
    supplierCost: 2.50,
    shippingDays: '5–8 days',
    shortDescription: 'Spread peanut butter, yogurt, or wet food and instantly calm an anxious dog. TikTok\'s most viral pet product.',
    description: 'The Calming Lick Mat is the easiest, fastest way to soothe an anxious dog. Whether it\'s bath time, thunderstorms, vet visits, or just a high-energy evening — spread any soft treat on the textured surface and watch your dog relax in minutes. Licking releases endorphins naturally, reducing stress without medication.',
    features: [
      { icon: '😌', title: 'Anxiety Relief', desc: 'Natural endorphin release through licking' },
      { icon: '🛁', title: 'Bath Time Hero', desc: 'Stick to the wall for hands-free bathing' },
      { icon: '🌿', title: 'Food-Grade Silicone', desc: '100% safe, BPA-free, dishwasher safe' },
      { icon: '🧲', title: 'Suction Cup Mount', desc: 'Sticks to walls, floors, or tub sides' },
    ],
    reviews: [
      { name: 'Jessica T.', rating: 5, date: 'May 2026', text: 'My anxious dog is now calm during thunderstorms because I give her peanut butter on this mat. Absolute lifesaver. Bought 3 more as gifts.' },
      { name: 'Marcus D.', rating: 5, date: 'May 2026', text: 'Game changer for bath time. My dog HATED baths. Now he\'s too busy licking to care. Wish I found this years ago.' },
      { name: 'Amy P.', rating: 5, date: 'March 2026', text: 'So simple but so effective. I freeze yogurt in it for a summer treat. My dog goes absolutely nuts for it.' },
    ],
  },
  {
    id: 3,
    slug: 'portable-paw-cleaner',
    name: 'Portable Paw Cleaner',
    shortName: 'Paw Cleaner',
    category: 'Dogs',
    tag: 'Grooming',
    price: 22.99,
    comparePrice: 34.99,
    rating: 4.7,
    reviewCount: 876,
    badge: 'New Arrival',
    badgeColor: 'bg-sky-500',
    image: IMGS.pawCleaner,
    images: [IMGS.pawCleaner, `${AE}/Sfd938aac34fa4011ac64fa47c6ecac5bT.jpg_960x960q75.jpg`, `${AE}/Se3a1ed1518434648ba6903882d573afcY.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Size', options: ['Small (up to 15 lbs)', 'Medium (15–50 lbs)', 'Large (50+ lbs)'] },
    ],
    emoji: '🐕',
    stock: 34,
    soldCount: 876,
    supplier: 'CJDropshipping',
    supplierProductId: '1661977359978860544',
    supplierProductUrl: 'https://cjdropshipping.com/product/2-in-1-dog-paw-cleaner-cup-soft-pet-dog-foot-cleaning-washer-brush-cup-portable-pet-foot-washer-paw-clean-brush-foot-cleaning-bucket-pet-products-p-1661977359978860544.html',
    supplierCost: 4.00,
    shippingDays: '5–8 days',
    shortDescription: 'Clean muddy paws in 5 seconds at the front door. Soft silicone bristles are gentle enough for daily use.',
    description: 'No more muddy floors, no more frantic wipe-downs. Our Portable Paw Cleaner fits right by your front door. Just add a little water, twist your dog\'s paw inside, and the 360° soft silicone bristles do all the work. Clean paws in under 5 seconds.',
    features: [
      { icon: '⚡', title: '5-Second Clean', desc: 'Faster than any towel or wipe' },
      { icon: '🌸', title: 'Paw-Friendly', desc: 'Soft silicone bristles, zero irritation' },
      { icon: '💧', title: 'Leak-Proof Lid', desc: 'Won\'t spill in your bag or car' },
      { icon: '📏', title: '3 Sizes', desc: 'Small, Medium, Large — fits any breed' },
    ],
    reviews: [
      { name: 'Rachel B.', rating: 5, date: 'May 2026', text: 'Worth every penny. My golden retriever loves playing in mud and this thing saves my floors every single day.' },
      { name: 'Chris V.', rating: 4, date: 'April 2026', text: 'Really well made. My dog was suspicious at first but got used to it after 2-3 uses. Now he just sticks his paw in without a fuss.' },
      { name: 'Dana H.', rating: 5, date: 'March 2026', text: 'Bought the large for my German shepherd and it fits perfectly. Simple concept but brilliantly executed.' },
    ],
  },
  {
    id: 4,
    slug: 'silent-cat-water-fountain',
    name: 'Silent Cat Water Fountain',
    shortName: 'Cat Fountain',
    category: 'Cats',
    tag: 'Health',
    price: 54.99,
    comparePrice: 79.99,
    rating: 4.8,
    reviewCount: 3102,
    badge: 'Top Rated',
    badgeColor: 'bg-violet-500',
    image: IMGS.catFountain,
    images: [IMGS.catFountain, `${AE}/S461dbcc3d1e24121b0eb1d0b14a9bac2R.png_960x960.png`, `${AE}/S0f55a30d5eae42f9a9470c515b295275N.png_960x960.png`],
    emoji: '🐱',
    stock: 22,
    soldCount: 3102,
    supplier: 'CJDropshipping',
    supplierProductId: 'D885D946-07B7-41B4-A333-35E334AFCB1D',
    supplierProductUrl: 'https://cjdropshipping.com/product/automatic-pet-cat-water-fountain-with-led-lighting-usb-dogs-cats-mute-drinker-feeder-bowl-drinking-dispenser-p-D885D946-07B7-41B4-A333-35E334AFCB1D.html',
    supplierCost: 14.00,
    shippingDays: '5–8 days',
    shortDescription: 'Vet-recommended circulating fountain that encourages cats to drink more water. Triple filtration, whisper-quiet.',
    description: 'Cats evolved in deserts and instinctively prefer running water over standing water. Most cats are chronically dehydrated, leading to kidney disease and urinary issues. Our Silent Cat Water Fountain mimics a natural stream, encouraging cats to drink 3x more, with a whisper-quiet (< 30 dB) pump and triple-filtration system.',
    features: [
      { icon: '🤫', title: 'Whisper Quiet', desc: 'Under 30 dB — won\'t disturb sleep' },
      { icon: '🔬', title: 'Triple Filtration', desc: 'Removes chlorine, hair, and impurities' },
      { icon: '💧', title: '2.5L Capacity', desc: 'Perfect for multi-cat households' },
      { icon: '🌙', title: 'LED Indicator', desc: 'Soft night light, signals low water' },
    ],
    reviews: [
      { name: 'Olivia C.', rating: 5, date: 'May 2026', text: 'My cat ignored his water bowl for years. This fountain? He\'s obsessed. Our vet said his kidney numbers improved at his last checkup. Incredible.' },
      { name: 'James F.', rating: 5, date: 'April 2026', text: 'So quiet I forget it\'s running. My two cats fight over who gets to drink from it first. Worth every dollar.' },
      { name: 'Patricia N.', rating: 5, date: 'March 2026', text: 'Easy to set up, easy to clean, and my picky cat approved it immediately.' },
    ],
  },
  {
    id: 5,
    slug: 'safeglow-led-collar',
    name: 'SafeGlow LED Collar',
    shortName: 'LED Collar',
    category: 'Dogs',
    tag: 'Safety',
    price: 24.99,
    comparePrice: 39.99,
    rating: 4.9,
    reviewCount: 1567,
    badge: 'Safety Pick',
    badgeColor: 'bg-yellow-500',
    image: IMGS.ledCollar,
    images: [IMGS.ledCollar, `${AE}/Sa74b9dc04d9944f1bc2f159ea0793d27y.jpg_960x960q75.jpg`, `${AE}/S3ae6d743f41744a996d89ef3cfbd875fr.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Size', options: ['S (10–14")', 'M (14–18")', 'L (18–24")', 'XL (24–30")'] },
      { type: 'Color', options: ['Blue', 'Red', 'Green', 'Pink', 'White'] },
    ],
    emoji: '✨',
    stock: 61,
    soldCount: 1567,
    supplier: 'CJDropshipping',
    supplierProductId: '7BFA65D8-41B6-4316-A7F4-2EB2A34CA257',
    supplierProductUrl: 'https://cjdropshipping.com/product/nylon-led-pet-dog-luminous-collar-night-safety-flashing-glow-in-dark-dog-cat-leash-adjustable-pet-supplies-p-7BFA65D8-41B6-4316-A7F4-2EB2A34CA257.html',
    supplierCost: 3.50,
    shippingDays: '5–8 days',
    shortDescription: 'Visible up to 1,500 feet away. USB rechargeable, waterproof, and 3 light modes for ultimate night safety.',
    description: 'Every year thousands of dogs are injured on nighttime walks because drivers can\'t see them. The SafeGlow LED Collar changes that. With 3 light modes and visibility up to 1,500 feet, drivers see your dog from over 4 football fields away. USB rechargeable, IPX6 waterproof, comfortable enough to wear all night.',
    features: [
      { icon: '🔦', title: '1,500 ft Visibility', desc: 'Seen from over 4 football fields away' },
      { icon: '🔋', title: 'USB Rechargeable', desc: 'No battery changes, ever' },
      { icon: '🌊', title: 'IPX6 Waterproof', desc: 'Rain, puddles, rivers — no problem' },
      { icon: '💡', title: '3 Light Modes', desc: 'Steady, slow flash, fast flash' },
    ],
    reviews: [
      { name: 'Mike R.', rating: 5, date: 'May 2026', text: 'Peace of mind on every nighttime walk. Super bright, holds charge for 3-4 nights, and my dog doesn\'t notice he\'s wearing it.' },
      { name: 'Sandra K.', rating: 5, date: 'April 2026', text: 'Cars actually slow down when they see my dog now. I\'ve had three neighbors ask where I got it.' },
      { name: 'Derek W.', rating: 5, date: 'March 2026', text: 'Great quality collar overall. The LED strip is bright without being annoyingly bright.' },
    ],
  },

  // ─── DOGS ─────────────────────────────────────────────────────────────────
  {
    id: 6,
    slug: 'orthopedic-memory-foam-dog-bed',
    name: 'Orthopedic Memory Foam Dog Bed',
    shortName: 'Orthopedic Dog Bed',
    category: 'Dogs',
    tag: 'Comfort',
    price: 79.99,
    comparePrice: 129.99,
    rating: 4.8,
    reviewCount: 2314,
    badge: 'Vet Approved',
    badgeColor: 'bg-brand-500',
    image: IMGS.dogBed,
    images: [IMGS.dogBed, `${AE}/Sf47a4f5e12014eadb35510dd97551a87y.jpg_960x960q75.jpg`, `${AE}/S713fa2da18604cf4a0e9a33a61fa098aZ.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Size', options: ['Small (24"×18")', 'Medium (32"×24")', 'Large (40"×30")', 'XL (48"×36")'] },
      { type: 'Color', options: ['Gray', 'Brown', 'Navy', 'Cream'] },
    ],
    emoji: '🛏️',
    stock: 38,
    soldCount: 2314,
    supplier: 'CJDropshipping',
    supplierProductId: '1816414774319009792',
    supplierProductUrl: 'https://cjdropshipping.com/product/bedsure-orthopedic-dog-bed-for-dogs-waterproof-dog-sofa-beds-medium-supportive-foam-pet-couch-bed-p-1816414774319009792.html',
    supplierCost: 22.00,
    shippingDays: '7–12 days',
    shortDescription: '4-inch memory foam relieves joint pain and supports aging dogs. Removable, machine-washable cover.',
    description: 'Dogs with arthritis, hip dysplasia, or joint pain deserve proper support while they sleep. Our Orthopedic Memory Foam Dog Bed uses certified CertiPUR-US foam to distribute weight evenly, reduce pressure points, and give your dog the deep, restorative sleep they need. The raised bolster edges provide a sense of security for anxious dogs.',
    features: [
      { icon: '🦴', title: 'Joint Relief', desc: '4-inch memory foam for arthritis & hip dysplasia' },
      { icon: '🧺', title: 'Machine Washable', desc: 'Removable cover, easy to keep fresh' },
      { icon: '🌡️', title: 'Temperature Neutral', desc: 'Doesn\'t trap heat like cheap foam' },
      { icon: '📏', title: '4 Sizes', desc: 'S, M, L, XL — up to 120 lbs' },
    ],
    reviews: [
      { name: 'Brenda T.', rating: 5, date: 'May 2026', text: 'My 12-year-old lab gets up so much easier in the morning. I can\'t believe the difference this bed made in just two weeks.' },
      { name: 'Paul M.', rating: 5, date: 'April 2026', text: 'Bought the XL for my Great Dane. Held up perfectly, and he chose it immediately over his old bed.' },
      { name: 'Nancy K.', rating: 4, date: 'March 2026', text: 'Great bed, ships well. My dog took two days to accept it but now won\'t leave it.' },
    ],
  },
  {
    id: 7,
    slug: 'self-cleaning-slicker-brush',
    name: 'Self-Cleaning Slicker Brush',
    shortName: 'Slicker Brush',
    category: 'Dogs',
    tag: 'Grooming',
    price: 18.99,
    comparePrice: 29.99,
    rating: 4.7,
    reviewCount: 1876,
    badge: null,
    badgeColor: null,
    image: IMGS.slickerBrush,
    images: [IMGS.slickerBrush, `${AE}/Sd852b4bc4dc04855908d23ce8bdb701c4.jpg_960x960q75.jpg`, `${AE}/S8a6322cacedd42ce9e21c0b0de0fb1ddp.jpg_960x960q75.jpg`],
    emoji: '🪮',
    stock: 112,
    soldCount: 1876,
    supplier: 'CJDropshipping',
    supplierProductId: '1561538210651066368',
    supplierProductUrl: 'https://cjdropshipping.com/product/pet-pumpkin-brush-pet-grooming-self-cleaning-slicker-brush-for-dogs-cats-puppy-rabbit-cat-brush-grooming-gently-removes-loose-undercoat-mats-tangled-hair-slicker-brush-p-1561538210651066368.html',
    supplierCost: 3.50,
    shippingDays: '5–8 days',
    shortDescription: 'Press a button and fur ejects instantly. Fine steel pins detangle, de-shed, and leave coats gleaming.',
    description: 'Grooming should be enjoyable for both of you. Our Self-Cleaning Slicker Brush features ultra-fine bent steel pins that glide through tangles without scratching skin. When you\'re done, just press the button — the retractable pin pad pushes all the fur off in one go. No more picking hair out of a brush for 5 minutes.',
    features: [
      { icon: '🔘', title: 'One-Click Clean', desc: 'Fur releases instantly at the press of a button' },
      { icon: '🎯', title: 'Fine Steel Pins', desc: 'Removes loose fur and tangles simultaneously' },
      { icon: '🤲', title: 'Ergonomic Grip', desc: 'Non-slip handle, comfortable for long sessions' },
      { icon: '🐕', title: 'All Coat Types', desc: 'Works on short, medium, and long fur' },
    ],
    reviews: [
      { name: 'Kelly S.', rating: 5, date: 'May 2026', text: 'The self-cleaning feature is a game-changer. My golden sheds constantly and this brush collects so much in one pass.' },
      { name: 'John D.', rating: 5, date: 'April 2026', text: 'My husky actually enjoys being brushed now because this doesn\'t pull like our old brush did. 10/10.' },
      { name: 'Fiona R.', rating: 4, date: 'March 2026', text: 'Good quality brush. The self-clean mechanism works well. Would recommend for medium to long-haired dogs.' },
    ],
  },
  {
    id: 8,
    slug: 'retractable-pro-dog-leash',
    name: 'Retractable Pro Dog Leash',
    shortName: 'Retractable Leash',
    category: 'Dogs',
    tag: 'Outdoor',
    price: 29.99,
    comparePrice: 44.99,
    rating: 4.6,
    reviewCount: 943,
    badge: null,
    badgeColor: null,
    image: IMGS.dogLeash,
    images: [IMGS.dogLeash, `${AE}/Sbcf31a45b6854f5f823250726ef89eceo.jpg_960x960q75.jpg`, `${AE}/S9f1a7658431846d6badd4bfd2aeaf8e36.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Length', options: ['10 ft (small breeds)', '16 ft (medium breeds)', '26 ft (large breeds)'] },
      { type: 'Color', options: ['Black', 'Blue', 'Red', 'Pink'] },
    ],
    emoji: '🦮',
    stock: 75,
    soldCount: 943,
    supplier: 'CJDropshipping',
    supplierProductId: '1417723948015161344',
    supplierProductUrl: 'https://cjdropshipping.com/product/dog-leash-retractable-leash-and-dog-collar-spotlight-automatic-pet-dog-cat-traction-rope-for-small-medium-dogs-pet-product-p-1417723948015161344.html',
    supplierCost: 6.00,
    shippingDays: '5–8 days',
    shortDescription: 'Heavy-duty 16-foot retractable leash with one-handed brake lock and tangle-resistant nylon cord.',
    description: 'Give your dog freedom to explore without losing control. Our Retractable Pro Leash extends up to 16 feet with a smooth, tangle-resistant nylon cord rated for dogs up to 110 lbs. The ergonomic handle features a one-handed brake and lock mechanism — freeze your dog\'s range instantly with a single thumb press.',
    features: [
      { icon: '📏', title: '16-Foot Reach', desc: 'Plenty of freedom on trails and parks' },
      { icon: '🛑', title: 'Instant Brake', desc: 'One-thumb lock, zero fumbling' },
      { icon: '💪', title: '110 lb Rated', desc: 'Heavy-duty cord for large breeds' },
      { icon: '💡', title: 'LED Torch', desc: 'Built-in flashlight for night walks' },
    ],
    reviews: [
      { name: 'Tyler B.', rating: 5, date: 'May 2026', text: 'Best retractable leash I\'ve owned. The brake is super responsive and the cord hasn\'t tangled once in 3 months.' },
      { name: 'Maria L.', rating: 4, date: 'April 2026', text: 'Good quality, comfortable handle. My 70lb lab can\'t pull it out of my hand. The LED is a nice bonus.' },
      { name: 'Greg H.', rating: 5, date: 'March 2026', text: 'Replaced 3 cheap leashes with this one. Zero regrets.' },
    ],
  },
  {
    id: 9,
    slug: 'crinkle-squeaky-toy-bundle',
    name: 'Crinkle Squeaky Toy Bundle',
    shortName: 'Squeaky Toy Bundle',
    category: 'Dogs',
    tag: 'Toys',
    price: 16.99,
    comparePrice: 27.99,
    rating: 4.8,
    reviewCount: 3210,
    badge: 'Best Value',
    badgeColor: 'bg-orange-500',
    image: IMGS.squeakyToys,
    images: [IMGS.squeakyToys, `${AE}/Sc895309997904d0e9f23a94aa59211c7n.jpg_960x960q75.jpg`, `${AE}/S136679bd58204bac93f422c64cc127754.jpg_960x960q75.jpg`],
    emoji: '🧸',
    stock: 200,
    soldCount: 3210,
    supplier: 'CJDropshipping',
    supplierProductId: 'F50D3B82-7E7C-48C9-97B6-1BD9A040AFF9',
    supplierProductUrl: 'https://cjdropshipping.com/product/dog-chew-toys-for-small-large-dogs-bite-resistant-dog-squeaky-duck-toys-interactive-squeak-puppy-dog-toy-pets-supplies-pet-products-p-F50D3B82-7E7C-48C9-97B6-1BD9A040AFF9.html',
    supplierCost: 3.50,
    shippingDays: '5–8 days',
    shortDescription: 'Set of 5 plush squeaky toys with crinkle textures dogs obsess over. Built to withstand aggressive chewers.',
    description: 'Every dog needs a toy collection — and this bundle gives them five in one go. Each toy features a double-reinforced stitched seam, a loud squeaker, and a crinkle interior that dogs find irresistible. The variety of shapes (duck, bone, fish, star, hedgehog) keeps your dog guessing and prevents boredom.',
    features: [
      { icon: '🎁', title: '5-Piece Set', desc: 'Duck, bone, fish, star, and hedgehog' },
      { icon: '🔊', title: 'Loud Squeaker', desc: 'Keeps dogs engaged and excited' },
      { icon: '🪡', title: 'Double-Stitched', desc: 'Reinforced seams for aggressive chewers' },
      { icon: '🌿', title: 'Non-Toxic', desc: 'Safe dyes, tested for pet safety' },
    ],
    reviews: [
      { name: 'Abby S.', rating: 5, date: 'May 2026', text: 'My dog carries the duck everywhere. These toys have lasted 2 months with daily play — impressive.' },
      { name: 'Ron F.', rating: 5, date: 'April 2026', text: 'Great value for a set of 5. My golden puppy has destroyed other toys in minutes but these held up.' },
      { name: 'Cathy W.', rating: 4, date: 'March 2026', text: 'All 5 toys are great quality. One squeaker stopped working after a month but everything else is solid.' },
    ],
  },
  {
    id: 12,
    slug: 'iq-puzzle-feeder-toy',
    name: 'IQ Puzzle Feeder Toy',
    shortName: 'Puzzle Feeder',
    category: 'Dogs',
    tag: 'Enrichment',
    price: 27.99,
    comparePrice: 39.99,
    rating: 4.8,
    reviewCount: 1432,
    badge: null,
    badgeColor: null,
    image: IMGS.puzzleFeeder,
    images: [IMGS.puzzleFeeder, `${AE}/Sce65839a727841a39aa1c48941d6b586J.jpg_960x960q75.jpg`, `${AE}/Sdebdfb33971941659426a6ae3ecdac6dL.jpg_960x960q75.jpg`],
    emoji: '🧩',
    stock: 64,
    soldCount: 1432,
    supplier: 'CJDropshipping',
    supplierProductId: '1753982835490304000',
    supplierProductUrl: 'https://cjdropshipping.com/product/food-dispensing-dog-toy-tumbler-leaky-food-ball-puzzle-toys-interactive-slowly-feeding-protect-stomach-increase-intelligence-pets-toy-pet-products-p-1753982835490304000.html',
    supplierCost: 5.00,
    shippingDays: '5–8 days',
    shortDescription: 'Tire out a high-energy dog mentally in 15 minutes. 3 difficulty levels, dishwasher safe.',
    description: 'A tired dog is a well-behaved dog — and mental exhaustion is 10x more effective than physical exercise. Our IQ Puzzle Feeder Toy challenges dogs to slide, spin, and flip compartments to reveal hidden treats. Three difficulty levels keep the challenge fresh as your dog gets smarter.',
    features: [
      { icon: '🧠', title: '3 Difficulty Levels', desc: 'Beginner to expert — scales with your dog' },
      { icon: '⚡', title: 'Burns Mental Energy', desc: '15 min of puzzles = 1 hour of running' },
      { icon: '✨', title: 'Dishwasher Safe', desc: 'BPA-free plastic, easy cleanup' },
      { icon: '🐾', title: 'All Breeds', desc: 'Works for dogs of any size and age' },
    ],
    reviews: [
      { name: 'Claire B.', rating: 5, date: 'May 2026', text: 'My hyperactive border collie is calm after 20 minutes with this toy. Nothing else has come close to wearing him out mentally.' },
      { name: 'Dan L.', rating: 5, date: 'April 2026', text: 'My lab mastered level 1 in a day and is working on level 2. Great quality, great concept.' },
      { name: 'Molly S.', rating: 4, date: 'March 2026', text: 'Love this for my senior dog — keeps his mind sharp. Some treats get stuck in corners but it\'s worth it.' },
    ],
  },
  {
    id: 13,
    slug: 'dog-car-seat-hammock',
    name: 'Dog Car Seat Hammock',
    shortName: 'Car Hammock',
    category: 'Dogs',
    tag: 'Travel',
    price: 49.99,
    comparePrice: 69.99,
    rating: 4.7,
    reviewCount: 2109,
    badge: null,
    badgeColor: null,
    image: IMGS.carHammock,
    images: [IMGS.carHammock, `${AE}/S7ad2ce9c0d28435ba5c51138d43f10a13.png`, `${AE}/S3964ec60a9344a0482371cea1ea5ee42v.png`],
    emoji: '🚗',
    stock: 48,
    soldCount: 2109,
    supplier: 'CJDropshipping',
    supplierProductId: '3E328406-8772-4CDD-A3BA-E8E1195888B9',
    supplierProductUrl: 'https://cjdropshipping.com/product/dog-car-seat-cover-view-mesh-pet-carrier-hammock-safety-protector-car-rear-back-seat-mat-with-zipper-and-pocket-for-travel-p-3E328406-8772-4CDD-A3BA-E8E1195888B9.html',
    supplierCost: 10.00,
    shippingDays: '5–8 days',
    shortDescription: 'Waterproof hammock converts your back seat into a safe, scratch-free dog zone. Installs in 2 minutes.',
    description: 'Protect your car\'s back seats and keep your dog safe on every trip. Our Dog Car Seat Hammock creates a comfortable, contained travel space that keeps dogs from sliding off seats or jumping into the front. The 600D waterproof Oxford fabric wipes clean in seconds and attaches to any headrest in under 2 minutes.',
    features: [
      { icon: '🛡️', title: 'Seat Protection', desc: 'Scratch-proof, waterproof 600D Oxford fabric' },
      { icon: '⚡', title: '2-Min Install', desc: 'Universal headrest straps fit any car' },
      { icon: '🐾', title: 'Mesh Window', desc: 'Dog can see you, you can see them' },
      { icon: '💧', title: 'Waterproof', desc: 'Wipes clean, machine washable too' },
    ],
    reviews: [
      { name: 'Emma J.', rating: 5, date: 'May 2026', text: 'My two labs used to destroy my back seat on every road trip. This hammock is indestructible and fits perfectly.' },
      { name: 'Kevin R.', rating: 5, date: 'April 2026', text: 'Easy to install and my dog actually seems calmer in the car now that he has his own defined space.' },
      { name: 'Susan W.', rating: 4, date: 'March 2026', text: 'Really solid product. Wish the side flaps were a bit bigger but overall excellent quality.' },
    ],
  },
  {
    id: 14,
    slug: 'collapsible-travel-bowl-set',
    name: 'Collapsible Travel Bowl Set',
    shortName: 'Travel Bowls',
    category: 'Dogs',
    tag: 'Travel',
    price: 14.99,
    comparePrice: 22.99,
    rating: 4.6,
    reviewCount: 4311,
    badge: null,
    badgeColor: null,
    image: IMGS.travelBowls,
    images: [IMGS.travelBowls, `${AE}/Scaf10d852c2545cd9eeb887d67929581P.jpg_960x960q75.jpg`, `${AE}/Scc740e010af64876940a231455349963W.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Color', options: ['Blue', 'Green', 'Pink', 'Gray'] },
    ],
    emoji: '🥤',
    stock: 280,
    soldCount: 4311,
    supplier: 'CJDropshipping',
    supplierProductId: '1698602629309411328',
    supplierProductUrl: 'https://cjdropshipping.com/product/portable-silicone-double-dog-food-bowls-foldable-non-slip-cat-bowl-pet-travel-anti-choking-feeding-bowl-outdoor-p-1698602629309411328.html',
    supplierCost: 2.50,
    shippingDays: '5–8 days',
    shortDescription: 'Pack of 2 silicone bowls fold flat to 1 inch. Clip to any bag. Perfect for hikes, travel, and vet visits.',
    description: 'Never leave home without water or food for your dog again. These food-grade silicone bowls collapse flat to just 1 inch thick and clip onto any bag or belt loop. Expand in one second for water or food, collapse and rinse in another second. The carabiner clip keeps them handy without taking up space.',
    features: [
      { icon: '📐', title: 'Folds Flat', desc: 'Collapses to 1 inch — packs in any pocket' },
      { icon: '🪣', title: '2-Bowl Set', desc: 'Separate bowls for food and water' },
      { icon: '🔗', title: 'Carabiner Clip', desc: 'Attaches to backpack, belt, or stroller' },
      { icon: '🌿', title: 'Food-Grade Silicone', desc: 'BPA-free, dishwasher safe' },
    ],
    reviews: [
      { name: 'Heather M.', rating: 5, date: 'May 2026', text: 'These go in my hiking pack every single time. Lightweight, easy to clean, and my dog loves them.' },
      { name: 'Aaron P.', rating: 5, date: 'April 2026', text: 'Genius design. I clip them to my leash bag and forget they\'re there until I need them.' },
      { name: 'Julia F.', rating: 4, date: 'March 2026', text: 'Great value for a 2-pack. Minor quibble: the carabiner is a bit stiff but it works fine.' },
    ],
  },
  {
    id: 15,
    slug: 'reflective-step-in-harness',
    name: 'Reflective Step-In Harness',
    shortName: 'Step-In Harness',
    category: 'Dogs',
    tag: 'Safety',
    price: 32.99,
    comparePrice: 49.99,
    rating: 4.8,
    reviewCount: 1789,
    badge: null,
    badgeColor: null,
    image: IMGS.harness,
    images: [IMGS.harness, `${AE}/S285380c911bc45048435cb87526cce14j.jpg_960x960q75.jpg`, `${AE}/S088109914f5d4449be0bc15982b9acb52.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Size', options: ['XS (12–16")', 'S (16–20")', 'M (20–26")', 'L (26–32")', 'XL (32–40")'] },
      { type: 'Color', options: ['Black', 'Red', 'Blue', 'Pink', 'Orange'] },
    ],
    emoji: '🦺',
    stock: 82,
    soldCount: 1789,
    supplier: 'CJDropshipping',
    supplierProductId: '1395687229984215040',
    supplierProductUrl: 'https://cjdropshipping.com/product/personalized-dog-harness-no-pull-reflective-breathable-adjustable-pet-harness-for-small-large-dog-harness-vest-with-custom-p-1395687229984215040.html',
    supplierCost: 7.00,
    shippingDays: '5–8 days',
    shortDescription: 'No-pull step-in design with 360° reflective stitching. No more collar pressure on the trachea.',
    description: 'Collars put pressure on your dog\'s trachea — harnesses distribute force across the chest and back, making walks safer and more comfortable. Our Reflective Step-In Harness features a no-pull front clip, 360° reflective stitching for night visibility, and a step-in design that most dogs accept without resistance.',
    features: [
      { icon: '🚫', title: 'No-Pull Design', desc: 'Front clip redirects pulling automatically' },
      { icon: '🔆', title: '360° Reflective', desc: 'Seen from all angles at night' },
      { icon: '🎽', title: 'Step-In Style', desc: 'Most dogs accept it without resistance' },
      { icon: '📏', title: '5 Sizes', desc: 'XS through XL — chest girth 12"–40"' },
    ],
    reviews: [
      { name: 'Tina L.', rating: 5, date: 'May 2026', text: 'My dog used to choke herself pulling on a collar. This harness stopped pulling behavior almost immediately.' },
      { name: 'Oliver G.', rating: 5, date: 'April 2026', text: 'Great quality stitching, easy to put on, and the reflective material is genuinely bright. Love it.' },
      { name: 'Zoe C.', rating: 4, date: 'March 2026', text: 'Fits my beagle perfectly using the size guide. The front clip works as advertised.' },
    ],
  },

  // ─── CATS ─────────────────────────────────────────────────────────────────
  {
    id: 17,
    slug: 'feather-wand-cat-teaser',
    name: 'Feather Wand Cat Teaser',
    shortName: 'Feather Wand',
    category: 'Cats',
    tag: 'Toys',
    price: 11.99,
    comparePrice: 18.99,
    rating: 4.8,
    reviewCount: 6720,
    badge: null,
    badgeColor: null,
    image: IMGS.featherWand,
    images: [IMGS.featherWand, `${AE}/Sc508e040e5634dda96bc922a7c46ed8dg.jpg_960x960q75.jpg`, `${AE}/Sc09ad92aaba049b68ae5d12f4c39f9b9W.jpg_960x960q75.jpg`],
    emoji: '🪶',
    stock: 420,
    soldCount: 6720,
    supplier: 'CJDropshipping',
    supplierProductId: '1603580763163865088',
    supplierProductUrl: 'https://cjdropshipping.com/product/tease-cat-toy-feather-pole-bell-p-1603580763163865088.html',
    supplierCost: 1.50,
    shippingDays: '5–8 days',
    shortDescription: 'Extendable 36-inch wand with realistic feather lure. Triggers your cat\'s natural hunt instinct instantly.',
    description: 'Even the laziest cat goes wild for a feather wand — it triggers deep-wired hunting instincts that no other toy can match. Our 36-inch extendable wand lets you create unpredictable movements from a comfortable distance. The realistic feather lure mimics bird behavior, keeping your cat engaged for a full interactive play session.',
    features: [
      { icon: '🪶', title: 'Realistic Feathers', desc: 'Mimics bird movement, triggers prey drive' },
      { icon: '📏', title: '36-Inch Wand', desc: 'Extended reach, comfortable for you' },
      { icon: '🎯', title: 'Unpredictable Motion', desc: 'Flexible tip creates erratic movement' },
      { icon: '🔄', title: 'Replaceable Lure', desc: 'Swap out feathers when they wear out' },
    ],
    reviews: [
      { name: 'Nina B.', rating: 5, date: 'May 2026', text: 'My indoor cat is finally getting exercise. She goes absolutely feral for this thing every evening.' },
      { name: 'Alex K.', rating: 5, date: 'April 2026', text: 'My 10-year-old cat plays like a kitten with this. Nothing else gets her off the couch.' },
      { name: 'Vera S.', rating: 4, date: 'March 2026', text: 'Great toy, my cat loves it. The feathers did shed a bit but nothing problematic.' },
    ],
  },
  {
    id: 18,
    slug: 'cat-window-perch-hammock',
    name: 'Cat Window Perch Hammock',
    shortName: 'Window Perch',
    category: 'Cats',
    tag: 'Comfort',
    price: 29.99,
    comparePrice: 44.99,
    rating: 4.7,
    reviewCount: 2876,
    badge: null,
    badgeColor: null,
    image: IMGS.windowPerch,
    images: [IMGS.windowPerch, `${AE}/S0024591c12fa41ac954fdf8a71f340b89.jpg_960x960q75.jpg`, `${AE}/Sfc0c918d4c2c4ffaa17206d4e3f205242.jpg_960x960q75.jpg`],
    emoji: '🪟',
    stock: 148,
    soldCount: 2876,
    supplier: 'CJDropshipping',
    supplierProductId: 'B4FEBB70-FA93-4D25-B65E-DBC617D2A157',
    supplierProductUrl: 'https://cjdropshipping.com/product/cat-bed-cat-hammock-p-B4FEBB70-FA93-4D25-B65E-DBC617D2A157.html',
    supplierCost: 6.00,
    shippingDays: '5–8 days',
    shortDescription: 'Suction-cup window seat for cats up to 25 lbs. Gives indoor cats a "bird TV" station they\'ll use all day.',
    description: 'Indoor cats crave stimulation — and there\'s no better entertainment than watching birds, squirrels, and the outside world from a sunny window perch. Our Window Hammock attaches with industrial-strength suction cups rated for 50 lbs, giving even the heaviest cats a secure, warm lounging spot right where they want to be.',
    features: [
      { icon: '🪟', title: 'Suction Cup Mount', desc: 'Industrial-strength, no drilling required' },
      { icon: '☀️', title: 'Prime Sun Spot', desc: 'Cats soak up vitamin D and warmth' },
      { icon: '🐦', title: '\'Bird TV\'', desc: 'Best enrichment for indoor cats' },
      { icon: '🧺', title: 'Washable Pad', desc: 'Removable fleece pad, machine washable' },
    ],
    reviews: [
      { name: 'Carla T.', rating: 5, date: 'May 2026', text: 'My cat is on this perch every morning watching the birds. The suction cups have held up for 6 months.' },
      { name: 'Mia F.', rating: 5, date: 'April 2026', text: 'Best $30 I\'ve spent on my cat. She\'s no longer knocking things off my window sill.' },
      { name: 'Henry B.', rating: 4, date: 'March 2026', text: 'My 18-pound cat has been on this daily for 3 months. The suction cups haven\'t budged.' },
    ],
  },
  {
    id: 19,
    slug: 'interactive-automatic-laser-toy',
    name: 'Interactive Automatic Laser Toy',
    shortName: 'Auto Laser Toy',
    category: 'Cats',
    tag: 'Toys',
    price: 22.99,
    comparePrice: 34.99,
    rating: 4.6,
    reviewCount: 3540,
    badge: null,
    badgeColor: null,
    image: IMGS.laserToy,
    images: [IMGS.laserToy, `${AE}/S16eae996e29648bf9abe0a98dc29ebcfY.jpg`, `${AE}/Sf7ceec2b7a0f4c1280f6eb03d68a1a7cI.jpg`],
    emoji: '🔴',
    stock: 167,
    soldCount: 3540,
    supplier: 'CJDropshipping',
    supplierProductId: '1399609489891659776',
    supplierProductUrl: 'https://cjdropshipping.com/product/automatic-cat-toys-interactive-smart-teasing-pet-led-laser-funny-p-1399609489891659776.html',
    supplierCost: 5.00,
    shippingDays: '5–8 days',
    shortDescription: 'Rotating laser plays with your cat automatically on 3 speed settings. Auto-off after 15 minutes.',
    description: 'Keep your cat entertained even when you\'re busy. Our Automatic Laser Toy rotates a class-safe laser dot in unpredictable patterns across floors, walls, and ceilings — triggering your cat\'s hunt instinct without any effort from you. Three speed settings, plus an auto-shutoff after 15 minutes prevents overstimulation.',
    features: [
      { icon: '🔄', title: 'Auto-Rotation', desc: 'Unpredictable patterns keep cats engaged' },
      { icon: '⏱️', title: '15-Min Auto-Off', desc: 'Prevents overstimulation automatically' },
      { icon: '🎚️', title: '3 Speed Modes', desc: 'Match your cat\'s energy level' },
      { icon: '🔋', title: 'USB Rechargeable', desc: 'No AA batteries ever again' },
    ],
    reviews: [
      { name: 'Tara M.', rating: 5, date: 'May 2026', text: 'My cat goes insane for this. I put it on while I work and she\'s entertained for the full 15 minutes.' },
      { name: 'Louis R.', rating: 4, date: 'April 2026', text: 'Great concept, works as advertised. My cat figured out the pattern after a few days on slow mode — switched to fast and she\'s hooked again.' },
      { name: 'Pam H.', rating: 5, date: 'March 2026', text: 'I have two cats and they both chase this simultaneously. Best cat toy I\'ve tried.' },
    ],
  },
  {
    id: 20,
    slug: 'premium-cat-carrier-backpack',
    name: 'Premium Cat Carrier Backpack',
    shortName: 'Cat Backpack',
    category: 'Cats',
    tag: 'Travel',
    price: 59.99,
    comparePrice: 89.99,
    rating: 4.8,
    reviewCount: 1923,
    badge: 'Top Rated',
    badgeColor: 'bg-violet-500',
    image: IMGS.catBackpack,
    images: [IMGS.catBackpack, `${AE}/S8ba24ba4c9b34db68582331f6bd066ae3.jpg_960x960q75.jpg`, `${AE}/Sfd28c0a541e148278dd05e8e0940760aM.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Color', options: ['Gray', 'Black', 'Blue', 'Green', 'Pink'] },
    ],
    emoji: '🎒',
    stock: 41,
    soldCount: 1923,
    supplier: 'CJDropshipping',
    supplierProductId: '1477560173949227008',
    supplierProductUrl: 'https://cjdropshipping.com/product/cat-carrier-bags-breathable-pet-carriers-dog-cat-backpack-travel-space-capsule-cage-pet-transport-bag-carrying-portable-outdoor-p-1477560173949227008.html',
    supplierCost: 15.00,
    shippingDays: '7–12 days',
    shortDescription: 'Bubble-window backpack lets your cat see the world without stress. Airline carry-on approved.',
    description: 'Travel with your cat without the stress — for either of you. Our Carrier Backpack features a panoramic bubble window your cat can peer out of, proper mesh ventilation, a padded interior, and enough room for cats up to 15 lbs. The ergonomic shoulder straps distribute weight evenly for long trips, and the design is airline carry-on approved.',
    features: [
      { icon: '🔵', title: 'Bubble Window', desc: 'Panoramic view keeps curious cats calm' },
      { icon: '💨', title: 'Mesh Ventilation', desc: 'Breathable on all sides' },
      { icon: '✈️', title: 'Airline Approved', desc: 'Fits under most airline seats' },
      { icon: '🎒', title: 'Ergonomic Straps', desc: 'Padded for long-distance comfort' },
    ],
    reviews: [
      { name: 'Chloe R.', rating: 5, date: 'May 2026', text: 'My cat actually looks relaxed when I take her out now. The bubble window is adorable and she loves watching the world go by.' },
      { name: 'Ian S.', rating: 5, date: 'April 2026', text: 'Took this on a flight. Perfect fit under the seat. My cat slept the whole way. Amazing product.' },
      { name: 'Kim T.', rating: 4, date: 'March 2026', text: 'Great backpack, super sturdy. The only thing I\'d improve is the interior padding — it could be a bit thicker.' },
    ],
  },
  {
    id: 22,
    slug: 'cat-deshedding-grooming-glove',
    name: 'Cat Deshedding Grooming Glove',
    shortName: 'Grooming Glove',
    category: 'Cats',
    tag: 'Grooming',
    price: 17.99,
    comparePrice: 27.99,
    rating: 4.8,
    reviewCount: 5103,
    badge: null,
    badgeColor: null,
    image: IMGS.groomingGlove,
    images: [IMGS.groomingGlove, `${AE}/Abdab5895245741c0b4a0257b6b5928dag.jpg_960x960q75.jpg`, `${AE}/A23492eac5889459cbc6da2e968d1c3d5d.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Color', options: ['Blue', 'Pink', 'Gray', 'Green'] },
    ],
    emoji: '🧤',
    stock: 195,
    soldCount: 5103,
    supplier: 'CJDropshipping',
    supplierProductId: '2503191148021601200',
    supplierProductUrl: 'https://cjdropshipping.com/product/pet-hair-remover-mitt-pet-hair-remover-gloves-deshedding-brush-glove-for-dog-cat-rabbit-with-long-short-curly-hair-p-2503191148021601200.html',
    supplierCost: 3.00,
    shippingDays: '5–8 days',
    shortDescription: 'Pet your cat and groom them simultaneously. Silicone tips collect loose fur — cats think it\'s a massage.',
    description: 'Cats that resist brushes often love the grooming glove because it feels like being petted by a large, friendly paw. Our deshedding glove features 255 flexible silicone tips that gently pull loose fur from the undercoat while your cat purrs contentedly. Works on short and long hair, and collected fur peels off in a neat ball.',
    features: [
      { icon: '🖐️', title: 'Feels Like Petting', desc: 'Cats relax instead of running away' },
      { icon: '🔵', title: '255 Silicone Tips', desc: 'Reaches deep into the undercoat' },
      { icon: '🐈', title: 'Long & Short Hair', desc: 'Works on all coat types' },
      { icon: '🧹', title: 'Easy Fur Removal', desc: 'Collected fur peels off in one piece' },
    ],
    reviews: [
      { name: 'Jess T.', rating: 5, date: 'May 2026', text: 'My cat used to hide when I brought out the brush. Now she runs toward me when she sees the glove.' },
      { name: 'Mark R.', rating: 5, date: 'April 2026', text: 'The amount of fur this collects in one session is genuinely shocking. Less fur on my couch, happier cat.' },
      { name: 'Lily S.', rating: 4, date: 'March 2026', text: 'Works great on my long-haired cat. The glove feels a bit large for my hand but it functions perfectly.' },
    ],
  },
  {
    id: 24,
    slug: 'cozy-cat-cave-hideaway',
    name: 'Cozy Cat Cave Hideaway',
    shortName: 'Cat Cave Bed',
    category: 'Cats',
    tag: 'Comfort',
    price: 44.99,
    comparePrice: 64.99,
    rating: 4.9,
    reviewCount: 3891,
    badge: null,
    badgeColor: null,
    image: IMGS.catCave,
    images: [IMGS.catCave, `${AE}/Seed4cf898ecb413db25b9f389ea5f494D.jpg_960x960q75.jpg`, `${AE}/S25c1378590ed418b82b05845d755703dp.jpg_960x960q75.jpg`],
    variants: [
      { type: 'Size', options: ['Small (up to 8 lbs)', 'Large (8–18 lbs)'] },
      { type: 'Color', options: ['Gray', 'Beige', 'Brown', 'Pink', 'Dark Gray'] },
    ],
    emoji: '🏠',
    stock: 59,
    soldCount: 3891,
    supplier: 'CJDropshipping',
    supplierProductId: '1483127811387559936',
    supplierProductUrl: 'https://cjdropshipping.com/product/honey-pot-cat-nest-cartoon-cat-bed-house-cave-lounger-for-cats-kittens-puppy-kennel-warm-closed-box-cute-pet-sleep-bag-small-dog-p-1483127811387559936.html',
    supplierCost: 11.00,
    shippingDays: '5–8 days',
    shortDescription: '100% natural wool felt cave gives anxious cats a dark, warm, enclosed safe space they instinctively seek.',
    description: 'Cats are denning animals — they feel safest in enclosed, dark, warm spaces. Our Cat Cave Hideaway is handcrafted from 100% natural New Zealand wool felt, which naturally regulates temperature (warm in winter, cool in summer) and is hypoallergenic. The rounded entrance and thick walls give cats the security that reduces anxiety dramatically.',
    features: [
      { icon: '🐑', title: '100% Wool Felt', desc: 'Handcrafted, hypoallergenic, temperature-regulating' },
      { icon: '🌡️', title: 'Self-Regulating', desc: 'Warm in winter, cooler in summer' },
      { icon: '😌', title: 'Anxiety Reducing', desc: 'Enclosed dark space = immediate calm' },
      { icon: '✋', title: 'Handmade', desc: 'Each cave is individually crafted' },
    ],
    reviews: [
      { name: 'Ellie G.', rating: 5, date: 'May 2026', text: 'My anxious rescue cat was in this cave within 10 minutes of it arriving. She sleeps in it every night now.' },
      { name: 'Noah R.', rating: 5, date: 'April 2026', text: 'The quality of the wool is outstanding. My two cats both somehow cram in together. It\'s adorable.' },
      { name: 'Julia M.', rating: 5, date: 'March 2026', text: 'Worth the price for the quality alone. My cat has never looked more relaxed.' },
    ],
  },
];

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug) || null;
}

export function getFeaturedProducts() {
  return products.filter((p) =>
    ['Best Seller', 'Fan Favorite', 'Top Rated'].includes(p.badge)
  );
}

export function getRelatedProducts(currentSlug, limit = 4) {
  const current = products.find((p) => p.slug === currentSlug);
  if (!current) return [];
  const sameCategory = products.filter(
    (p) => p.slug !== currentSlug && p.category === current.category
  );
  const others = products.filter(
    (p) => p.slug !== currentSlug && p.category !== current.category
  );
  return [...sameCategory, ...others].slice(0, limit);
}
